### ISSUE TITLE
Class Introductions

### ISSUE THREAD

**Issue by DiyahM** [hackbrightacademy/pt-frontend-fall-2015#1]
Hello! 
I'm one of the senior instructors for the Front End class. Professionally, I've been a software engineer for 15 years. I spent 11 years in the defense industry helping naval ships communicate with other and helping satellites get into space. The last four years, I've spent working on my own company, [Playpen Labs](http://playpenlabs.com). At Playpen Labs, I work with startups and nonprofits building web applications that are critical to their business success. I also spend a lot of time testing out product ideas, with the hopes of building a product based business vs our current service based business. 

I look forward to meeting and working with everyone this session. Please use this space to introduce yourself. Include your current profession, company (if applicable), and why you are taking this class.

-Hadiyah

**Comment by SofyaMulenok** [comment]
Hello everyone,

I hurried to post in a different spot, so I'll have to duplicate some of it :) 

My name is Sofya Mulenok, I currently work as a knowledge engineer (a linguist/web producer) at Ask.com in downtown Oakland.
I'm originally from Russia, and I've been in the USA for 4 years now.
I love traveling, learning languages (I've studied 5 besides my native one), most of my background is in translation and localization.

I'm taking this class in order to better explore the opportunities in the field I'm passionate about. I have been working in IT for about 4 years now, and my goal is to gradually transition into a more technical role.

Excited to meet everyone!
Sofya

**Comment by carolc** [comment]
Hi there!
My name is Carol. I grew up in suburbia Maryland and moved out here to sunny SF 3 years ago!

I am a full-time UI/UX Designer at an architecture design/e-commerce company called Houseplans. I design a lot of websites but am not so good at actually putting them together on that Internet thing. Other than that, I am a part-time illustrator, dancer, wine-drinker, and bunny-food-dispenser. 

Looking forward to getting to know everyone :)

Cheers,
Carol

**Comment by kbryerman** [comment]
Hey there!

My name is Karly Bryerman and I'm an architectural designer for STUDIOS Architecture. Some days I get to pick out textiles/tiles/furniture for that high tech client, other days I'm in charge of toilet fixture and urinal accessibility requirements (womp womp..). 

I've always been interested in programming, originally with visual scripting tools and then with front-end languages. But, after trying to learn on my own, I've realized that I need the structured environment of a class to really understand all the things. 

Outside of work, you can usually find me in the backyard tending to the herb garden or shooting the shit with my seven (7) roommates. 

Excited for next week!

Karly

**Comment by adynata** [comment]
Hi all!

My name's Claire, and I'm in the process of changing careers from one in horticulture to one in web development. I've spend the last few months learning Ruby and building things in Rails and am excited to add front end languages to my complement of skills.

Aside from plants, my background is in the arts. I make inflatable floating sculptures, confabricate imaginary institutions of higher learning, and in general work towards various incarnations of collaborative and creative community. I want to do more of that with code!

Excited to meet you all tomorrow!

**Comment by soumiafares** [comment]
Hi everyone!  Super excited to meet you all tomorrow :) My name is Soumia and I recently moved to SF from NYC.  Like many of you, I'm also taking this class for a career change of sorts.  Coming from a research background (academia/neuroscience and UX) and QA testing, I now want to be able to actually fix bugs on my own :)

More importantly, I hope, with the help of this class,  to be able to take a step in the right direction so that in the future, I can cook up some wonderful stuff I've been thinking of building (for social causes, especially) and make them come to life instead of just being ideas that live in my head.  

I am usually having a blast by watching films (especially foreign/indie), listening to live jazz, spending time on my yoga practice, cooking, catching a soccer game or biking! 

See you all tomorrow!

**Comment by JamieCorley** [comment]
Hello! I'm Jamie, a recent transplant to SF from Washington, D.C. where I worked as a press secretary in the U.S. Congress for 5+ years.  I'm diving headfirst into the world of programming.  I'm looking to develop a skill set that will help me build out ideas I've been thinking/working on.

I love going on hikes and being outside whenever possible.  I'm also an artist and spend lots of time painting in my little studio in the North Bay. 

Excited to meet everyone tonight!

**Comment by LindaMarie** [comment]
Hey future classmates,
I'm Linda, a bay area native. I currently work at Optimizely, Inc. as a product designer on our A/B testing platform. Other than design, my hobbies consist of collecting, restoring and selling mid-century moden furniture and various knick knacks with my husband Jon. 

I'm super stoked about this class! My main takeaway is to be able to build beautifully rich prototypes but heck, if I can start shipping production code– EVEN BETTER! 

Excited to meet you all!

**Comment by nmrosendin** [comment]
Hi everyone! I'm from the bay area and am currently working in tech as a product manager. In this class, I'm looking to strengthening my technical skills and be able to build my own prototypes, websites and personal projects. 

I love being outdoors - running or hiking, love to cook and have recently started painting again. Excited to meet you all as well!

**Comment by LijieZhou** [comment]
Hi everyone! I'm Lijie. I'm the associate instructor for our front-end class. Right now, I'm working on my master's degree in computer science. I'm a former entrepreneur doing my own education startup before I came back to school. I moved to SF one-and-half year ago and started learning programming by myself. Because of that, I know what students from a non-CS background struggle with, both technically and emotionally. Honestly, I struggled a lot and I would like to share my journey with you and make the best use of things I learnt from it. 
Beyond programming, I'm also an avid biker and home brewer. I am managing a small fund and would like to share some investment knowledge with you ladies.

**Comment by koreoliver** [comment]
Hi All! My name is Kore and I work freelance in content marketing, and I also work part time at a landscape design and installation company exploring an interest in design. I've worked as a project manager on some web development projects in the past, and the bits of coding I was exposed to were my favorite part of the work. I'd like to transition into technical roles in the future. It's been fun but challenging learning on my own, and I'm excited to learn in a classroom environment.

I love hiking, biking, cooking, traveling... Looking forward to meeting everyone as well!

**Comment by pineapplechiu** [comment]
Hello, everyone! I'm Paula and I enjoy working with maps and databases. I use databases everyday but find it hard to share data in easily digestible ways. I hope to learn new data visualization methods to share and show data. My favorite database is Postgres with a PostGIS extension! (And I use Oracle and Access for work.) I'm super excited meet everyone and see all the class projects by October.

**Comment by willis-meyers** [comment]
Hello! I'm Willis. I have been searching for ways to merge my art and tech career. I'm an IT Admin at Ticketfly and the founder/Board President of Aggregate Space Gallery. I moved to the Bay Area about a decade ago to pursue my MFA at San Francisco Art Institute and graduated in 2008. Through my MFA, I found that I loved troubleshooting and tinkering and pursued Helpdesk and IT work to pay the bills. Years later, here I am! Looking to marry my experience with Photoshop, Illustrator, HTML and CSS with my familiarity with services like Github and Slack through my Admin work. 
I have put a lot of energy into my gallery lately and helped transition us from an independent gallery to a 501c3 organization. We just had our first ever fundraiser this weekend and it went great! I now look forward to focusing on my own goals a bit more now with this class and with you all.

**Comment by demiskipper** [comment]
Hi! I know this is closed, but I figure I would introduce myself.  I was previously signed up for the Intro class but decided to switch into the Front End Class instead.

My name is Demi. I am currently working at Apple as a Data Analyst on the Maps Team.

I am really really excited to learn as much a humanly possible about programing and potentially move on to the full stack course once this is over.  In my free time I love to be outside, rock climb and hang out in Dolores Park :)
