### ISSUE TITLE
Website for a non-profit 

### ISSUE THREAD

**Issue by SofyaMulenok** [hackbrightacademy/pt-frontend-fall-2015#6]
I remember @willis-meyers mentioning she'd like to create a website for her art gallery.
I'd love to join! Sounds like a great opportunity to learn many things at once: working with images, meta-data positioning, etc.

**Comment by willis-meyers** [comment]
Sounds great @sofyamulenok !

**Comment by koreoliver** [comment]
@willis-meyers and @sofyamulenok I wanted to work on a non-profit and this sounds like a great project. I'd love to join your team if you'd like a third!

**Comment by willis-meyers** [comment]
Looking forward to having you on board, @koreoliver! It will be great to work with you. @SofyaMulenok and Kore: I am unable to come to class tonight due to a personal matter, but am excited to work with you both! In lieu of today, I will be at the next Code Brunch and studying up on the slides from tonight. I would love to chat with you both Wednesday to see what direction you would like to go in to help build your portfolios. 

Re: content, if you wanted to go with building an art gallery NFP and lift content from my gallery, I have many beautiful high res images that we can play with and will bring them along when we start our project.

In addition, here is a sample of a responsive Drupal site for a gallery I know: https://www.soex.org/index.php. And, here is an example of a NFP that is currently rebuilding their site (Drupal with SFDC/custom Springboard integration) to make it more responsive: http://bavc.org/ . Looking forward to hearing where you both want to go with this!

**Comment by DiyahM** [comment]
Hey Guys! Thanks for being proactive about picking a project and team. As this team now has 3 members, I'm going to close this thread.

Next steps:
1) One of you should create a repo under your own account and add team members as a collaborators.
2) Continue the discussion in the new repo using issues.
